name: Run Unit Tests

on: [push]

jobs: 
  run-unit-testS:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install PNPM
        - run: npm i -g pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      

      - run: pnpm ci

      - run: pnpm test
